project_id = "tpbnewkqwgfiyiluiyra"

[functions.generate-architecture]
verify_jwt = false

[functions.parse-resume]
verify_jwt = false

[functions.generate-content]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false
